# Generated by Django 2.1.4 on 2018-12-12 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Componist',
            fields=[
                ('componistid', models.IntegerField(db_column='componistID', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('bio', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'componist',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('serieid', models.IntegerField(db_column='serieID', primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255)),
                ('rating', models.IntegerField()),
                ('studio', models.CharField(max_length=255)),
                ('serienaam', models.CharField(db_column='serieNaam', max_length=255)),
            ],
            options={
                'db_table': 'serie',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('songid', models.IntegerField(db_column='songID', primary_key=True, serialize=False)),
                ('singer', models.CharField(max_length=255)),
                ('songnaam', models.CharField(db_column='songNaam', max_length=255)),
            ],
            options={
                'db_table': 'song',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Soundtrack',
            fields=[
                ('soundtrackid', models.IntegerField(db_column='soundtrackID', primary_key=True, serialize=False)),
                ('catagory', models.CharField(max_length=11)),
                ('rating', models.IntegerField()),
                ('description', models.CharField(max_length=11)),
            ],
            options={
                'db_table': 'soundtrack',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userid', models.AutoField(db_column='userID', primary_key=True, serialize=False)),
                ('nickname', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usercomponistfavorite',
            fields=[
                ('usercomponistfavoriteid', models.IntegerField(db_column='UserComponistFavoriteID', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'usercomponistfavorite',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usersoundtrackrating',
            fields=[
                ('usersoundtrackratingid', models.IntegerField(db_column='UserSoundtrackRatingID', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'usersoundtrackrating',
                'managed': False,
            },
        ),
    ]
